version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    tty: true
    restart: always
    depends_on:
      - front

  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    command: bash -c 'yarn install && yarn dev'

  api:
    container_name: api
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./api:/app
    expose:
      - 9000
    tty: true
    restart: always


networks:
  default:
    name: webapp-network